function cp(btn,text){navigator.clipboard.writeText(text).then(()=>{const o=btn.textContent;btn.textContent='copied';btn.classList.add('ok');setTimeout(()=>{btn.textContent=o;btn.classList.remove('ok')},1800)})}
const scene=document.getElementById('tscene');
if(scene){
const NYX_HDR=`<div style="display:flex;gap:1rem;margin-bottom:.7rem;padding-bottom:.7rem;border-bottom:1px solid #1a1a1a"><div style="white-space:pre;line-height:1.3;color:#a1a1a1;font-size:.8rem;flex-shrink:0"> /\\_/\\ \n( ·.· )\n > ♥ < </div><div style="display:flex;flex-direction:column;justify-content:center;gap:.05rem;font-size:.68rem"><span><span style="color:#ededed;font-weight:600">Localcode</span> <span style="color:#333">v4.0.0 · @localcode/cli</span></span><span><span style="color:#333">provider  </span><span style="color:#ededed">ollama</span><span style="color:#333">  qwen2.5-coder:7b</span></span><span><span style="color:#333">cwd       </span><span style="color:#888">~/projects/api</span></span><span><span style="color:#333">memory    </span><span style="color:#ededed">.localcode.md</span><span style="color:#333"> loaded</span></span></div></div>`;
const FRAMES=[[0,NYX_HDR],[200,`<div class="terminal-line"><span class="terminal-prompt">❯ </span><span class="terminal-text" id="tw1"></span><span class="cursor" id="tc1"></span></div>`],[300,null,'tw1','review src/routes/auth.ts',38,'tc1'],[1400,`<div class="terminal-line"><span class="terminal-icon">◈ </span><span style="color:#444">Reading </span><span style="color:#a1a1a1">src/routes/auth.ts</span><span style="color:#444"> (198 lines)</span></div>`],[2000,`<div class="terminal-line"><span class="terminal-icon">⟳ </span><span style="color:#888">read_file</span><span style="color:#444">  path='src/routes/auth.ts'</span></div>`],[2700,`<div class="terminal-line" style="margin-top:.2rem"><span style="color:#333">⚠ </span><span style="color:#a1a1a1">[HIGH] SQL injection risk on line 48</span></div>`],[3000,`<div class="terminal-line"><span style="color:#333">⚠ </span><span style="color:#a1a1a1">[MED]  No rate limiting on /login</span></div>`],[3300,`<div class="terminal-line"><span style="color:#444">  </span><span style="color:#a1a1a1">[LOW]  Unused import: bcryptjs</span></div>`],[3800,`<div class="terminal-line" style="margin-top:.3rem"><span class="terminal-prompt">❯ </span><span class="terminal-text" id="tw2"></span><span class="cursor" id="tc2"></span></div>`],[4000,null,'tw2','/provider claude',38,'tc2'],[4900,`<div class="terminal-line"><span style="color:#28c840">✓ </span><span style="color:#444">Switched to </span><span style="color:#a1a1a1">claude-sonnet-4-5</span></div>`],[5400,`<div class="terminal-line" style="margin-top:.3rem"><span class="terminal-prompt">❯ </span><span class="terminal-text" id="tw3"></span><span class="cursor" id="tc3"></span></div>`],[5600,null,'tw3','/commit',38,'tc3'],[6300,`<div class="terminal-line"><span class="terminal-icon">⟳ </span><span style="color:#444">Generating commit from staged diff…</span></div>`],[7200,`<div class="terminal-line"><span style="color:#a1a1a1">✓ fix(auth): sanitize inputs + add rate limiting</span></div>`],[7600,`<div class="terminal-line"><span style="color:#444;font-size:.64rem">  Co-authored-by: Localcode &lt;localcode@thealxlabs.com&gt;</span></div>`],[8300,`<div class="terminal-line" style="margin-top:.3rem"><span class="terminal-prompt">❯ </span><span class="cursor"></span></div>`]];
let timeouts=[];
function clearAnim(){timeouts.forEach(clearTimeout);timeouts=[]}
function typeText(elId,text,msPerChar,cursorId){return new Promise(res=>{const el=document.getElementById(elId);if(!el){res();return}const cur=cursorId?document.getElementById(cursorId):null;let i=0;function tick(){if(!el){res();return}el.textContent=text.slice(0,i);i++;if(i<=text.length){timeouts.push(setTimeout(tick,msPerChar))}else{if(cur)cur.remove();res()}}tick()})}
function playTerminal(){clearAnim();scene.innerHTML='';FRAMES.forEach(([delay,html,twId,twText,twSpeed,tcId])=>{const t=setTimeout(async()=>{if(html){scene.insertAdjacentHTML('beforeend',html);scene.scrollTop=scene.scrollHeight}if(twId&&twText){await typeText(twId,twText,twSpeed||38,tcId);scene.scrollTop=scene.scrollHeight}},delay);timeouts.push(t)})}
const replayBtn=document.getElementById('replay-btn');
if(replayBtn)replayBtn.addEventListener('click',playTerminal);
playTerminal();
